/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tarea3pds;
import java.util.*;

public class App {

    public int suma(int a, int b) {
        return a+b;
    }

    //Funcion Main
    public static void main(String[] args) {
        Scanner input = new Scanner(System.in);
        ArrayList<Libro> biblioteca = new ArrayList<>();

        while(true){
            System.out.println("\n---------Bienvenido al Sistema de registro y busqueda de libros");
            System.out.println("Seleccione una de las opciones a realizar");
            System.out.println("[1]: Registrar un libro");
            System.out.println("[2]: Buscar un libro");
            System.out.println("[3]: Ver lista de todos los libros");
            System.out.println("[4]: Salir del programa");
            System.out.println("[5]: Hardcodear libro");
            String opcion = input.next().trim();

            int intOpcion;
            try {
                intOpcion = Integer.parseInt(opcion);
            }
            catch (Exception e) {
                System.out.println("Opcion invalida. Por favor intentelo nuevamente.");
                continue;
            }

            //Registrar libro
            if (intOpcion == 1){
             
                input.nextLine();
                System.out.println("\n--Ingrese el titulo del libro");
                String titulo = input.nextLine().trim();

                System.out.println("\n--Ingrese el autor del libro (separar con coma si es mas de uno)");
                String autor = input.nextLine();

                System.out.println("\n--Ingrese la fecha de edicion del libro");
                String fecha = input.nextLine();

                System.out.println("\n--Ingrese la cantidad de paginas del libro");
                String paginas = input.nextLine();

                System.out.println("\n--Ingrese la editorial del libro");
                String editorial = input.nextLine();

                System.out.println("\n--Ingrese el genero del libro");
                String genero = input.nextLine();

                System.out.println("\n--Ingrese el codigo ISBN del libro");
                String isbn = input.nextLine();

                System.out.println("\n--Ingrese la estante de la biblioteca donde esta libro");
                String estante = input.nextLine();

                System.out.println("\n--Ingrese el estado del libro (Prestado, Disponible o Extraviado)");
                String estado = input.nextLine();

                System.out.println("\n--Ingrese una descripcion del libro");
                String descripcion = input.nextLine();
                
                Libro nuevoLibro = new Libro(titulo, autor, fecha, paginas, editorial, genero, isbn, estante, estado, descripcion);
                System.out.println("\n***Libro registrado con exito***");
                System.out.println(nuevoLibro);
                
                biblioteca.add(nuevoLibro);

            }
            //Buscar Libro
            else if (intOpcion == 2){

            }
            //Ver Lista Libros
            else if (intOpcion == 3){
                int index = 0;
                System.out.println("\n------Lista de todos los Libros registrados");
                System.out.println("Ingrese el numero del libro con el que desea interactuar");
                while (index < biblioteca.size()){
                    System.out.println("[" + index + "]: " + biblioteca.get(index));
                    index += 1;
                }

                opcion = input.next().trim();
                try {
                intOpcion = Integer.parseInt(opcion);
                }
                catch (Exception e) {
                    System.out.println("Opcion invalida. Por favor intentelo nuevamente.");
                    continue;
                }

                if (intOpcion >= biblioteca.size() || intOpcion < 0){
                    System.out.println("Opcion invalida. Por favor intentelo nuevamente");
                }
                else{
                    
                }


            }
            //Salir
            else if (intOpcion == 4){
                break;
            }
            //Hardcodeo libro test
            else if (intOpcion == 5){
                Libro nuevoLibro = new Libro("Persona 5", "Atlus", "2017", 
                "107", "Sony", "RPG", "24", "M", "Disponible", "Bien weno el juego");
                biblioteca.add(nuevoLibro);
            }
            else{
                System.out.println("Opcion invalida. Por favor intentelo nuevamente");
                continue;
            }
        }
      

        input.close();
    }
}
